name: New Term
on: [workflow_dispatch]
jobs:
  submit_weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run new term script
        run: ./.github/scripts/new_term.sh
        shell: bash
