name: Submit Weekly
on: [workflow_dispatch]
jobs:
  submit_weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip wget
      - name: Install the pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb
          sudo dpkg -i pandoc-2.17.1.1-1-amd64.deb
      - name: Run submit weekly script
        run: ./.github/scripts/submit_weekly.sh
        shell: bash
      